// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/event.proto

package poc.endpoints.protobuf.v1.protowrapper;

public final class EventProtobufWrapper {
  private EventProtobufWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DeviceEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:poc.endpoints.protobuf.v1.protowrapper.DeviceEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string userid = 1;</code>
     */
    boolean hasUserid();
    /**
     * <code>required string userid = 1;</code>
     */
    java.lang.String getUserid();
    /**
     * <code>required string userid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUseridBytes();

    /**
     * <code>required fixed64 epochvalue = 2;</code>
     */
    boolean hasEpochvalue();
    /**
     * <code>required fixed64 epochvalue = 2;</code>
     */
    long getEpochvalue();

    /**
     * <code>required string deviceid = 3;</code>
     */
    boolean hasDeviceid();
    /**
     * <code>required string deviceid = 3;</code>
     */
    java.lang.String getDeviceid();
    /**
     * <code>required string deviceid = 3;</code>
     */
    com.google.protobuf.ByteString
        getDeviceidBytes();

    /**
     * <code>required fixed32 alert = 4;</code>
     */
    boolean hasAlert();
    /**
     * <code>required fixed32 alert = 4;</code>
     */
    int getAlert();

    /**
     * <code>required string bucketid = 5;</code>
     */
    boolean hasBucketid();
    /**
     * <code>required string bucketid = 5;</code>
     */
    java.lang.String getBucketid();
    /**
     * <code>required string bucketid = 5;</code>
     */
    com.google.protobuf.ByteString
        getBucketidBytes();

    /**
     * <code>required string class = 6;</code>
     */
    boolean hasClass_();
    /**
     * <code>required string class = 6;</code>
     */
    java.lang.String getClass_();
    /**
     * <code>required string class = 6;</code>
     */
    com.google.protobuf.ByteString
        getClass_Bytes();

    /**
     * <code>required string data = 7;</code>
     */
    boolean hasData();
    /**
     * <code>required string data = 7;</code>
     */
    java.lang.String getData();
    /**
     * <code>required string data = 7;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>required string eventcode = 8;</code>
     */
    boolean hasEventcode();
    /**
     * <code>required string eventcode = 8;</code>
     */
    java.lang.String getEventcode();
    /**
     * <code>required string eventcode = 8;</code>
     */
    com.google.protobuf.ByteString
        getEventcodeBytes();

    /**
     * <code>required fixed32 eventcounter = 9;</code>
     */
    boolean hasEventcounter();
    /**
     * <code>required fixed32 eventcounter = 9;</code>
     */
    int getEventcounter();

    /**
     * <code>required fixed64 eventtime = 10;</code>
     */
    boolean hasEventtime();
    /**
     * <code>required fixed64 eventtime = 10;</code>
     */
    long getEventtime();

    /**
     * <code>required fixed32 filesize = 11;</code>
     */
    boolean hasFilesize();
    /**
     * <code>required fixed32 filesize = 11;</code>
     */
    int getFilesize();

    /**
     * <code>required string id = 12;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 12;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 12;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required bool isdeleted = 13;</code>
     */
    boolean hasIsdeleted();
    /**
     * <code>required bool isdeleted = 13;</code>
     */
    boolean getIsdeleted();

    /**
     * <code>required string parentid = 14;</code>
     */
    boolean hasParentid();
    /**
     * <code>required string parentid = 14;</code>
     */
    java.lang.String getParentid();
    /**
     * <code>required string parentid = 14;</code>
     */
    com.google.protobuf.ByteString
        getParentidBytes();

    /**
     * <code>required string profileid = 15;</code>
     */
    boolean hasProfileid();
    /**
     * <code>required string profileid = 15;</code>
     */
    java.lang.String getProfileid();
    /**
     * <code>required string profileid = 15;</code>
     */
    com.google.protobuf.ByteString
        getProfileidBytes();

    /**
     * <code>required fixed32 storagemode = 16;</code>
     */
    boolean hasStoragemode();
    /**
     * <code>required fixed32 storagemode = 16;</code>
     */
    int getStoragemode();

    /**
     * <code>required fixed32 unit = 17;</code>
     */
    boolean hasUnit();
    /**
     * <code>required fixed32 unit = 17;</code>
     */
    int getUnit();

    /**
     * <code>required string value = 18;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 18;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 18;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code poc.endpoints.protobuf.v1.protowrapper.DeviceEvent}
   *
   * <pre>
   * Packet header message 
   * </pre>
   */
  public static final class DeviceEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:poc.endpoints.protobuf.v1.protowrapper.DeviceEvent)
      DeviceEventOrBuilder {
    // Use DeviceEvent.newBuilder() to construct.
    private DeviceEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeviceEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeviceEvent defaultInstance;
    public static DeviceEvent getDefaultInstance() {
      return defaultInstance;
    }

    public DeviceEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              userid_ = bs;
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              epochvalue_ = input.readFixed64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              deviceid_ = bs;
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              alert_ = input.readFixed32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              bucketid_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              class__ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              data_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              eventcode_ = bs;
              break;
            }
            case 77: {
              bitField0_ |= 0x00000100;
              eventcounter_ = input.readFixed32();
              break;
            }
            case 81: {
              bitField0_ |= 0x00000200;
              eventtime_ = input.readFixed64();
              break;
            }
            case 93: {
              bitField0_ |= 0x00000400;
              filesize_ = input.readFixed32();
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000800;
              id_ = bs;
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              isdeleted_ = input.readBool();
              break;
            }
            case 114: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00002000;
              parentid_ = bs;
              break;
            }
            case 122: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00004000;
              profileid_ = bs;
              break;
            }
            case 133: {
              bitField0_ |= 0x00008000;
              storagemode_ = input.readFixed32();
              break;
            }
            case 141: {
              bitField0_ |= 0x00010000;
              unit_ = input.readFixed32();
              break;
            }
            case 146: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00020000;
              value_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.internal_static_poc_endpoints_protobuf_v1_protowrapper_DeviceEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.internal_static_poc_endpoints_protobuf_v1_protowrapper_DeviceEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent.class, poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<DeviceEvent> PARSER =
        new com.google.protobuf.AbstractParser<DeviceEvent>() {
      public DeviceEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceEvent> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userid_;
    /**
     * <code>required string userid = 1;</code>
     */
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userid = 1;</code>
     */
    public java.lang.String getUserid() {
      java.lang.Object ref = userid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUseridBytes() {
      java.lang.Object ref = userid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EPOCHVALUE_FIELD_NUMBER = 2;
    private long epochvalue_;
    /**
     * <code>required fixed64 epochvalue = 2;</code>
     */
    public boolean hasEpochvalue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required fixed64 epochvalue = 2;</code>
     */
    public long getEpochvalue() {
      return epochvalue_;
    }

    public static final int DEVICEID_FIELD_NUMBER = 3;
    private java.lang.Object deviceid_;
    /**
     * <code>required string deviceid = 3;</code>
     */
    public boolean hasDeviceid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string deviceid = 3;</code>
     */
    public java.lang.String getDeviceid() {
      java.lang.Object ref = deviceid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string deviceid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceidBytes() {
      java.lang.Object ref = deviceid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALERT_FIELD_NUMBER = 4;
    private int alert_;
    /**
     * <code>required fixed32 alert = 4;</code>
     */
    public boolean hasAlert() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required fixed32 alert = 4;</code>
     */
    public int getAlert() {
      return alert_;
    }

    public static final int BUCKETID_FIELD_NUMBER = 5;
    private java.lang.Object bucketid_;
    /**
     * <code>required string bucketid = 5;</code>
     */
    public boolean hasBucketid() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string bucketid = 5;</code>
     */
    public java.lang.String getBucketid() {
      java.lang.Object ref = bucketid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bucketid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string bucketid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getBucketidBytes() {
      java.lang.Object ref = bucketid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bucketid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLASS_FIELD_NUMBER = 6;
    private java.lang.Object class__;
    /**
     * <code>required string class = 6;</code>
     */
    public boolean hasClass_() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string class = 6;</code>
     */
    public java.lang.String getClass_() {
      java.lang.Object ref = class__;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          class__ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string class = 6;</code>
     */
    public com.google.protobuf.ByteString
        getClass_Bytes() {
      java.lang.Object ref = class__;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        class__ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 7;
    private java.lang.Object data_;
    /**
     * <code>required string data = 7;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string data = 7;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string data = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTCODE_FIELD_NUMBER = 8;
    private java.lang.Object eventcode_;
    /**
     * <code>required string eventcode = 8;</code>
     */
    public boolean hasEventcode() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string eventcode = 8;</code>
     */
    public java.lang.String getEventcode() {
      java.lang.Object ref = eventcode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          eventcode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string eventcode = 8;</code>
     */
    public com.google.protobuf.ByteString
        getEventcodeBytes() {
      java.lang.Object ref = eventcode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventcode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTCOUNTER_FIELD_NUMBER = 9;
    private int eventcounter_;
    /**
     * <code>required fixed32 eventcounter = 9;</code>
     */
    public boolean hasEventcounter() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required fixed32 eventcounter = 9;</code>
     */
    public int getEventcounter() {
      return eventcounter_;
    }

    public static final int EVENTTIME_FIELD_NUMBER = 10;
    private long eventtime_;
    /**
     * <code>required fixed64 eventtime = 10;</code>
     */
    public boolean hasEventtime() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required fixed64 eventtime = 10;</code>
     */
    public long getEventtime() {
      return eventtime_;
    }

    public static final int FILESIZE_FIELD_NUMBER = 11;
    private int filesize_;
    /**
     * <code>required fixed32 filesize = 11;</code>
     */
    public boolean hasFilesize() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required fixed32 filesize = 11;</code>
     */
    public int getFilesize() {
      return filesize_;
    }

    public static final int ID_FIELD_NUMBER = 12;
    private java.lang.Object id_;
    /**
     * <code>required string id = 12;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required string id = 12;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 12;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISDELETED_FIELD_NUMBER = 13;
    private boolean isdeleted_;
    /**
     * <code>required bool isdeleted = 13;</code>
     */
    public boolean hasIsdeleted() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required bool isdeleted = 13;</code>
     */
    public boolean getIsdeleted() {
      return isdeleted_;
    }

    public static final int PARENTID_FIELD_NUMBER = 14;
    private java.lang.Object parentid_;
    /**
     * <code>required string parentid = 14;</code>
     */
    public boolean hasParentid() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>required string parentid = 14;</code>
     */
    public java.lang.String getParentid() {
      java.lang.Object ref = parentid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          parentid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string parentid = 14;</code>
     */
    public com.google.protobuf.ByteString
        getParentidBytes() {
      java.lang.Object ref = parentid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROFILEID_FIELD_NUMBER = 15;
    private java.lang.Object profileid_;
    /**
     * <code>required string profileid = 15;</code>
     */
    public boolean hasProfileid() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>required string profileid = 15;</code>
     */
    public java.lang.String getProfileid() {
      java.lang.Object ref = profileid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          profileid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string profileid = 15;</code>
     */
    public com.google.protobuf.ByteString
        getProfileidBytes() {
      java.lang.Object ref = profileid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        profileid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STORAGEMODE_FIELD_NUMBER = 16;
    private int storagemode_;
    /**
     * <code>required fixed32 storagemode = 16;</code>
     */
    public boolean hasStoragemode() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>required fixed32 storagemode = 16;</code>
     */
    public int getStoragemode() {
      return storagemode_;
    }

    public static final int UNIT_FIELD_NUMBER = 17;
    private int unit_;
    /**
     * <code>required fixed32 unit = 17;</code>
     */
    public boolean hasUnit() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>required fixed32 unit = 17;</code>
     */
    public int getUnit() {
      return unit_;
    }

    public static final int VALUE_FIELD_NUMBER = 18;
    private java.lang.Object value_;
    /**
     * <code>required string value = 18;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <code>required string value = 18;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 18;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userid_ = "";
      epochvalue_ = 0L;
      deviceid_ = "";
      alert_ = 0;
      bucketid_ = "";
      class__ = "";
      data_ = "";
      eventcode_ = "";
      eventcounter_ = 0;
      eventtime_ = 0L;
      filesize_ = 0;
      id_ = "";
      isdeleted_ = false;
      parentid_ = "";
      profileid_ = "";
      storagemode_ = 0;
      unit_ = 0;
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEpochvalue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAlert()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBucketid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClass_()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEventcode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEventcounter()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEventtime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFilesize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsdeleted()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParentid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProfileid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStoragemode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUnit()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUseridBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed64(2, epochvalue_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDeviceidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFixed32(4, alert_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getBucketidBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getClass_Bytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getDataBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getEventcodeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeFixed32(9, eventcounter_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeFixed64(10, eventtime_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeFixed32(11, filesize_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getIdBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBool(13, isdeleted_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(14, getParentidBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(15, getProfileidBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeFixed32(16, storagemode_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeFixed32(17, unit_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeBytes(18, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUseridBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, epochvalue_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDeviceidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(4, alert_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getBucketidBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getClass_Bytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getDataBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getEventcodeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(9, eventcounter_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(10, eventtime_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(11, filesize_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getIdBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, isdeleted_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getParentidBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getProfileidBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(16, storagemode_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(17, unit_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(18, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code poc.endpoints.protobuf.v1.protowrapper.DeviceEvent}
     *
     * <pre>
     * Packet header message 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:poc.endpoints.protobuf.v1.protowrapper.DeviceEvent)
        poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.internal_static_poc_endpoints_protobuf_v1_protowrapper_DeviceEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.internal_static_poc_endpoints_protobuf_v1_protowrapper_DeviceEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent.class, poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent.Builder.class);
      }

      // Construct using poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        epochvalue_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        alert_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        bucketid_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        class__ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        eventcode_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        eventcounter_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        eventtime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        filesize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        isdeleted_ = false;
        bitField0_ = (bitField0_ & ~0x00001000);
        parentid_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        profileid_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        storagemode_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        unit_ = 0;
        bitField0_ = (bitField0_ & ~0x00010000);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00020000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.internal_static_poc_endpoints_protobuf_v1_protowrapper_DeviceEvent_descriptor;
      }

      public poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent getDefaultInstanceForType() {
        return poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent.getDefaultInstance();
      }

      public poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent build() {
        poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent buildPartial() {
        poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent result = new poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.epochvalue_ = epochvalue_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.deviceid_ = deviceid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.alert_ = alert_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.bucketid_ = bucketid_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.class__ = class__;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.eventcode_ = eventcode_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.eventcounter_ = eventcounter_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.eventtime_ = eventtime_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.filesize_ = filesize_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.isdeleted_ = isdeleted_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.parentid_ = parentid_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.profileid_ = profileid_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.storagemode_ = storagemode_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.unit_ = unit_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent) {
          return mergeFrom((poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent other) {
        if (other == poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent.getDefaultInstance()) return this;
        if (other.hasUserid()) {
          bitField0_ |= 0x00000001;
          userid_ = other.userid_;
          onChanged();
        }
        if (other.hasEpochvalue()) {
          setEpochvalue(other.getEpochvalue());
        }
        if (other.hasDeviceid()) {
          bitField0_ |= 0x00000004;
          deviceid_ = other.deviceid_;
          onChanged();
        }
        if (other.hasAlert()) {
          setAlert(other.getAlert());
        }
        if (other.hasBucketid()) {
          bitField0_ |= 0x00000010;
          bucketid_ = other.bucketid_;
          onChanged();
        }
        if (other.hasClass_()) {
          bitField0_ |= 0x00000020;
          class__ = other.class__;
          onChanged();
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000040;
          data_ = other.data_;
          onChanged();
        }
        if (other.hasEventcode()) {
          bitField0_ |= 0x00000080;
          eventcode_ = other.eventcode_;
          onChanged();
        }
        if (other.hasEventcounter()) {
          setEventcounter(other.getEventcounter());
        }
        if (other.hasEventtime()) {
          setEventtime(other.getEventtime());
        }
        if (other.hasFilesize()) {
          setFilesize(other.getFilesize());
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000800;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasIsdeleted()) {
          setIsdeleted(other.getIsdeleted());
        }
        if (other.hasParentid()) {
          bitField0_ |= 0x00002000;
          parentid_ = other.parentid_;
          onChanged();
        }
        if (other.hasProfileid()) {
          bitField0_ |= 0x00004000;
          profileid_ = other.profileid_;
          onChanged();
        }
        if (other.hasStoragemode()) {
          setStoragemode(other.getStoragemode());
        }
        if (other.hasUnit()) {
          setUnit(other.getUnit());
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00020000;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserid()) {
          
          return false;
        }
        if (!hasEpochvalue()) {
          
          return false;
        }
        if (!hasDeviceid()) {
          
          return false;
        }
        if (!hasAlert()) {
          
          return false;
        }
        if (!hasBucketid()) {
          
          return false;
        }
        if (!hasClass_()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        if (!hasEventcode()) {
          
          return false;
        }
        if (!hasEventcounter()) {
          
          return false;
        }
        if (!hasEventtime()) {
          
          return false;
        }
        if (!hasFilesize()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        if (!hasIsdeleted()) {
          
          return false;
        }
        if (!hasParentid()) {
          
          return false;
        }
        if (!hasProfileid()) {
          
          return false;
        }
        if (!hasStoragemode()) {
          
          return false;
        }
        if (!hasUnit()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (poc.endpoints.protobuf.v1.protowrapper.EventProtobufWrapper.DeviceEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object userid_ = "";
      /**
       * <code>required string userid = 1;</code>
       */
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string userid = 1;</code>
       */
      public java.lang.String getUserid() {
        java.lang.Object ref = userid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUseridBytes() {
        java.lang.Object ref = userid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userid = 1;</code>
       */
      public Builder setUserid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userid = 1;</code>
       */
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userid_ = getDefaultInstance().getUserid();
        onChanged();
        return this;
      }
      /**
       * <code>required string userid = 1;</code>
       */
      public Builder setUseridBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userid_ = value;
        onChanged();
        return this;
      }

      private long epochvalue_ ;
      /**
       * <code>required fixed64 epochvalue = 2;</code>
       */
      public boolean hasEpochvalue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required fixed64 epochvalue = 2;</code>
       */
      public long getEpochvalue() {
        return epochvalue_;
      }
      /**
       * <code>required fixed64 epochvalue = 2;</code>
       */
      public Builder setEpochvalue(long value) {
        bitField0_ |= 0x00000002;
        epochvalue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 epochvalue = 2;</code>
       */
      public Builder clearEpochvalue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        epochvalue_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object deviceid_ = "";
      /**
       * <code>required string deviceid = 3;</code>
       */
      public boolean hasDeviceid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string deviceid = 3;</code>
       */
      public java.lang.String getDeviceid() {
        java.lang.Object ref = deviceid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string deviceid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceidBytes() {
        java.lang.Object ref = deviceid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string deviceid = 3;</code>
       */
      public Builder setDeviceid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceid = 3;</code>
       */
      public Builder clearDeviceid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceid_ = getDefaultInstance().getDeviceid();
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceid = 3;</code>
       */
      public Builder setDeviceidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceid_ = value;
        onChanged();
        return this;
      }

      private int alert_ ;
      /**
       * <code>required fixed32 alert = 4;</code>
       */
      public boolean hasAlert() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required fixed32 alert = 4;</code>
       */
      public int getAlert() {
        return alert_;
      }
      /**
       * <code>required fixed32 alert = 4;</code>
       */
      public Builder setAlert(int value) {
        bitField0_ |= 0x00000008;
        alert_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 alert = 4;</code>
       */
      public Builder clearAlert() {
        bitField0_ = (bitField0_ & ~0x00000008);
        alert_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object bucketid_ = "";
      /**
       * <code>required string bucketid = 5;</code>
       */
      public boolean hasBucketid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string bucketid = 5;</code>
       */
      public java.lang.String getBucketid() {
        java.lang.Object ref = bucketid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bucketid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string bucketid = 5;</code>
       */
      public com.google.protobuf.ByteString
          getBucketidBytes() {
        java.lang.Object ref = bucketid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bucketid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string bucketid = 5;</code>
       */
      public Builder setBucketid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        bucketid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string bucketid = 5;</code>
       */
      public Builder clearBucketid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        bucketid_ = getDefaultInstance().getBucketid();
        onChanged();
        return this;
      }
      /**
       * <code>required string bucketid = 5;</code>
       */
      public Builder setBucketidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        bucketid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object class__ = "";
      /**
       * <code>required string class = 6;</code>
       */
      public boolean hasClass_() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string class = 6;</code>
       */
      public java.lang.String getClass_() {
        java.lang.Object ref = class__;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            class__ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string class = 6;</code>
       */
      public com.google.protobuf.ByteString
          getClass_Bytes() {
        java.lang.Object ref = class__;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          class__ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string class = 6;</code>
       */
      public Builder setClass_(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        class__ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string class = 6;</code>
       */
      public Builder clearClass_() {
        bitField0_ = (bitField0_ & ~0x00000020);
        class__ = getDefaultInstance().getClass_();
        onChanged();
        return this;
      }
      /**
       * <code>required string class = 6;</code>
       */
      public Builder setClass_Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        class__ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>required string data = 7;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string data = 7;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string data = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string data = 7;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string data = 7;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000040);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>required string data = 7;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        data_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object eventcode_ = "";
      /**
       * <code>required string eventcode = 8;</code>
       */
      public boolean hasEventcode() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string eventcode = 8;</code>
       */
      public java.lang.String getEventcode() {
        java.lang.Object ref = eventcode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            eventcode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string eventcode = 8;</code>
       */
      public com.google.protobuf.ByteString
          getEventcodeBytes() {
        java.lang.Object ref = eventcode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventcode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string eventcode = 8;</code>
       */
      public Builder setEventcode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        eventcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string eventcode = 8;</code>
       */
      public Builder clearEventcode() {
        bitField0_ = (bitField0_ & ~0x00000080);
        eventcode_ = getDefaultInstance().getEventcode();
        onChanged();
        return this;
      }
      /**
       * <code>required string eventcode = 8;</code>
       */
      public Builder setEventcodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        eventcode_ = value;
        onChanged();
        return this;
      }

      private int eventcounter_ ;
      /**
       * <code>required fixed32 eventcounter = 9;</code>
       */
      public boolean hasEventcounter() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required fixed32 eventcounter = 9;</code>
       */
      public int getEventcounter() {
        return eventcounter_;
      }
      /**
       * <code>required fixed32 eventcounter = 9;</code>
       */
      public Builder setEventcounter(int value) {
        bitField0_ |= 0x00000100;
        eventcounter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 eventcounter = 9;</code>
       */
      public Builder clearEventcounter() {
        bitField0_ = (bitField0_ & ~0x00000100);
        eventcounter_ = 0;
        onChanged();
        return this;
      }

      private long eventtime_ ;
      /**
       * <code>required fixed64 eventtime = 10;</code>
       */
      public boolean hasEventtime() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required fixed64 eventtime = 10;</code>
       */
      public long getEventtime() {
        return eventtime_;
      }
      /**
       * <code>required fixed64 eventtime = 10;</code>
       */
      public Builder setEventtime(long value) {
        bitField0_ |= 0x00000200;
        eventtime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 eventtime = 10;</code>
       */
      public Builder clearEventtime() {
        bitField0_ = (bitField0_ & ~0x00000200);
        eventtime_ = 0L;
        onChanged();
        return this;
      }

      private int filesize_ ;
      /**
       * <code>required fixed32 filesize = 11;</code>
       */
      public boolean hasFilesize() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required fixed32 filesize = 11;</code>
       */
      public int getFilesize() {
        return filesize_;
      }
      /**
       * <code>required fixed32 filesize = 11;</code>
       */
      public Builder setFilesize(int value) {
        bitField0_ |= 0x00000400;
        filesize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 filesize = 11;</code>
       */
      public Builder clearFilesize() {
        bitField0_ = (bitField0_ & ~0x00000400);
        filesize_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 12;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required string id = 12;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 12;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 12;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 12;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000800);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 12;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        id_ = value;
        onChanged();
        return this;
      }

      private boolean isdeleted_ ;
      /**
       * <code>required bool isdeleted = 13;</code>
       */
      public boolean hasIsdeleted() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required bool isdeleted = 13;</code>
       */
      public boolean getIsdeleted() {
        return isdeleted_;
      }
      /**
       * <code>required bool isdeleted = 13;</code>
       */
      public Builder setIsdeleted(boolean value) {
        bitField0_ |= 0x00001000;
        isdeleted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isdeleted = 13;</code>
       */
      public Builder clearIsdeleted() {
        bitField0_ = (bitField0_ & ~0x00001000);
        isdeleted_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object parentid_ = "";
      /**
       * <code>required string parentid = 14;</code>
       */
      public boolean hasParentid() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>required string parentid = 14;</code>
       */
      public java.lang.String getParentid() {
        java.lang.Object ref = parentid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            parentid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string parentid = 14;</code>
       */
      public com.google.protobuf.ByteString
          getParentidBytes() {
        java.lang.Object ref = parentid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parentid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string parentid = 14;</code>
       */
      public Builder setParentid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        parentid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string parentid = 14;</code>
       */
      public Builder clearParentid() {
        bitField0_ = (bitField0_ & ~0x00002000);
        parentid_ = getDefaultInstance().getParentid();
        onChanged();
        return this;
      }
      /**
       * <code>required string parentid = 14;</code>
       */
      public Builder setParentidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        parentid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object profileid_ = "";
      /**
       * <code>required string profileid = 15;</code>
       */
      public boolean hasProfileid() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>required string profileid = 15;</code>
       */
      public java.lang.String getProfileid() {
        java.lang.Object ref = profileid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            profileid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string profileid = 15;</code>
       */
      public com.google.protobuf.ByteString
          getProfileidBytes() {
        java.lang.Object ref = profileid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          profileid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string profileid = 15;</code>
       */
      public Builder setProfileid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        profileid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string profileid = 15;</code>
       */
      public Builder clearProfileid() {
        bitField0_ = (bitField0_ & ~0x00004000);
        profileid_ = getDefaultInstance().getProfileid();
        onChanged();
        return this;
      }
      /**
       * <code>required string profileid = 15;</code>
       */
      public Builder setProfileidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        profileid_ = value;
        onChanged();
        return this;
      }

      private int storagemode_ ;
      /**
       * <code>required fixed32 storagemode = 16;</code>
       */
      public boolean hasStoragemode() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>required fixed32 storagemode = 16;</code>
       */
      public int getStoragemode() {
        return storagemode_;
      }
      /**
       * <code>required fixed32 storagemode = 16;</code>
       */
      public Builder setStoragemode(int value) {
        bitField0_ |= 0x00008000;
        storagemode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 storagemode = 16;</code>
       */
      public Builder clearStoragemode() {
        bitField0_ = (bitField0_ & ~0x00008000);
        storagemode_ = 0;
        onChanged();
        return this;
      }

      private int unit_ ;
      /**
       * <code>required fixed32 unit = 17;</code>
       */
      public boolean hasUnit() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>required fixed32 unit = 17;</code>
       */
      public int getUnit() {
        return unit_;
      }
      /**
       * <code>required fixed32 unit = 17;</code>
       */
      public Builder setUnit(int value) {
        bitField0_ |= 0x00010000;
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 unit = 17;</code>
       */
      public Builder clearUnit() {
        bitField0_ = (bitField0_ & ~0x00010000);
        unit_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 18;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <code>required string value = 18;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 18;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 18;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 18;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00020000);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 18;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:poc.endpoints.protobuf.v1.protowrapper.DeviceEvent)
    }

    static {
      defaultInstance = new DeviceEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:poc.endpoints.protobuf.v1.protowrapper.DeviceEvent)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poc_endpoints_protobuf_v1_protowrapper_DeviceEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_poc_endpoints_protobuf_v1_protowrapper_DeviceEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/resources/event.proto\022&poc.en" +
      "dpoints.protobuf.v1.protowrapper\"\305\002\n\013Dev" +
      "iceEvent\022\016\n\006userid\030\001 \002(\t\022\022\n\nepochvalue\030\002" +
      " \002(\006\022\020\n\010deviceid\030\003 \002(\t\022\r\n\005alert\030\004 \002(\007\022\020\n" +
      "\010bucketid\030\005 \002(\t\022\r\n\005class\030\006 \002(\t\022\014\n\004data\030\007" +
      " \002(\t\022\021\n\teventcode\030\010 \002(\t\022\024\n\014eventcounter\030" +
      "\t \002(\007\022\021\n\teventtime\030\n \002(\006\022\020\n\010filesize\030\013 \002" +
      "(\007\022\n\n\002id\030\014 \002(\t\022\021\n\tisdeleted\030\r \002(\010\022\020\n\010par" +
      "entid\030\016 \002(\t\022\021\n\tprofileid\030\017 \002(\t\022\023\n\013storag" +
      "emode\030\020 \002(\007\022\014\n\004unit\030\021 \002(\007\022\r\n\005value\030\022 \002(\t",
      "B\026B\024EventProtobufWrapper"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_poc_endpoints_protobuf_v1_protowrapper_DeviceEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_poc_endpoints_protobuf_v1_protowrapper_DeviceEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_poc_endpoints_protobuf_v1_protowrapper_DeviceEvent_descriptor,
        new java.lang.String[] { "Userid", "Epochvalue", "Deviceid", "Alert", "Bucketid", "Class_", "Data", "Eventcode", "Eventcounter", "Eventtime", "Filesize", "Id", "Isdeleted", "Parentid", "Profileid", "Storagemode", "Unit", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
